export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    AUTHORIZE_REQUEST: 'USER_AUTHORIZE_REQUEST',
    AUTHORIZE_SUCCESS: 'USER_AUTHORIZE_SUCCESS',
    AUTHORIZE_FAILURE: 'USER_AUTHORIZE_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    CHANGE_USER_NAME: 'CHANGE_USER_NAME'
};